### ISSUE TITLE
Trash directory not found error

### ISSUE THREAD

**Issue by jsmm** [wxxedu/obsidianki4#7]
Hi there! After last update, obsidianki4 gives error in macOS because it cannot find a `.trash` directory. MacOS doesn't allow the user to create hidden files with such name because it is reserved for the sytem. Would it be possible for obsidianki4 to give users the option to enter the name of their trash folder? 

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.38 (355e4cd5) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-02-08 23:58:07
Add-ons possibly involved: ⁨Obsidianki 4 Move Your Obsidian Vault into Anki⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/macbook/Library/Application Support/Anki2/addons21/620260832/__init__.py", line 192, in onOk
    anki_importer.importer(my_files_catalog)
  File "/Users/macbook/Library/Application Support/Anki2/addons21/620260832/anki_importer.py", line 14, in importer
    empty_trash()
  File "/Users/macbook/Library/Application Support/Anki2/addons21/620260832/anki_importer.py", line 137, in empty_trash
    trash_directories = os.listdir(trash_can_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/macbook/Documents/Obsidian/Vault/.trash'
```

**Comment by wxxedu** [comment]
I am so sorry about the late reply!
You can turn on the trash folder in Obsidian's settings.
<img width="1440" alt="iShot2021-02-25 10 08 55" src="https://user-images.githubusercontent.com/36021591/109092435-7b529c80-7751-11eb-845d-f5a705c45382.png">

**Comment by tretofane** [comment]
I have the same error when use "save and convert" button. 
My Obsidian settings already  is set to use obsidian's trash. So the error during vault conversion seems to research elsewhere
Have you some suggestions?
Regards
